name: data512
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - pandas
  - matplotlib
  - seaborn
  - jupyter
prefix: /opt/anaconda3/envs/data512
